[tools]
# DevOps Tools
k9s = "latest"
aws-cli = "latest"
kubectl = "latest"
terraform = "latest"
helm = "latest"

# Languages & Runtimes
go = "1.25.5" 
node = "24.12.0"      
python = "3.14.0"   

# CLI Power Tools
fzf = "latest"
ripgrep = "latest"  
starship = "latest"
usage = "latest"

