# --- General ---
add_newline = true

# --- Tool & Env Modules (The "Mise" View) ---
[golang]
symbol = "ğŸ¹ "
format = "via [$symbol($version )]($style)"
style = "bold cyan"

[python]
symbol = "ğŸ "
format = "via [$symbol($version )]($style)"

[terraform]
symbol = "ó±¢ "
format = "via [$symbol($workspace )]($style)"

# --- DevOps Modules ---
[kubernetes]
symbol = "â˜¸ï¸ "
disabled = false
format = 'at [$symbol$context( \($namespace\))]($style) '
style = "bold blue"

[aws]
symbol = "ó°¸ "
format = 'on [$symbol($profile )(\($region\) )]($style)'

# --- Git Section ---
[git_branch]
symbol = "ï˜ "
style = "bold purple"

[git_status]
style = "red"
format = '([\[$all_status$ahead_behind\]]($style) )'

# --- The Prompt ---
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"